import com.fasterxml.jackson.core.JsonProcessingException;
import dev.emirman.util.payment.garanti.service.callback.CallBackService;
import dev.emirman.util.payment.garanti.service.callback.ICallBackService;
import org.junit.jupiter.api.Test;

import java.util.Base64;

public class ValidateCallBackTest {
    @Test
    public void validate() throws JsonProcessingException {
        String encodedCallBackBody = "eyJ4aWQiOiJiMWZkY2M4Ni1mNjJhLTQ1ZTAtYWI1MS04MzU0MjUzMWIxYmEiLCJtZHN0YXR1cyI6IjEiLCJtZGVycm9ybWVzc2FnZSI6Ilktc3RhdHVzL0NoYWxsZW5nZSBhdXRoZW50aWNhdGlvbiB2aWEgQUNTOiBodHRwczovL2diZW12M2RzZWN1cmUuZ2FyYW50aS5jb20udHIvd2ViL2NyZXEiLCJ0eG5zdGF0dXMiOiIiLCJlY2kiOiIwNSIsImNhdnYiOiJBQUlCQXBjaE13QUFBQ2lkbEpGeWRBQUFBQUE9IiwicGFyZXNzeW50YXhvayI6IiIsInBhcmVzdmVyaWZpZWQiOiIiLCJ2ZXJzaW9uIjoiIiwiaXJlcWNvZGUiOiIiLCJpcmVxZGV0YWlsIjoiIiwidmVuZG9yY29kZSI6IiIsImNhdnZhbGdvcml0aG0iOiIiLCJtZCI6ImFXNWtaWGc2TURKdmhoZmhpZEZHbmFITHg3T2t1WElKeHhnYjNGbkR4ZmVLOFlzY1VJUnpicWpuRjFmZjVGZjdZV0pSS3dydjAvSmxDN05pQjRYc3NjZXZpSVZVbkZVRXdkNFZlZG9Nay8ySTVTbEp1Yk5NaWV4WVZsMnltRExGby9KdWpjdTU0c3RMc1JENjl1dzMyUi93K0ZWU3JlY2ZyYUU3a3doM2NXWlFlcG4wWlZwTGdKakZ4VVd5VzJ5clhiUTJXQm11MGVFcit5bmdpTENtUVowRi9OMFlxRFRiIiwidGVybWluYWxpZCI6WyIzMDY5MTI5NyIsIjMwNjkxMjk3Il0sIm9pZCI6IjFhYjJmOTAyLTU2MmItNGY1YS1iOTdkLTY2NWJiOGFlOTg1ZiIsImF1dGhjb2RlIjoiMTAzMzI3IiwicmVzcG9uc2UiOiJBcHByb3ZlZCIsImVycm1zZyI6IiIsImhvc3Rtc2ciOiIiLCJwcm9jcmV0dXJuY29kZSI6IjAwIiwidHJhbnNpZCI6IjFhYjJmOTAyLTU2MmItNGY1YS1iOTdkLTY2NWJiOGFlOTg1ZiIsImhvc3RyZWZudW0iOiIzMTcyMDkwMzk3MTAiLCJybmQiOiJwL2k4QWpwVmdSS21FWHJNSkYyQyIsImhhc2giOiJVRlIvTE5BZHc5NWpJaDVVRUJudzVaSXVvVFE9IiwiaGFzaHBhcmFtcyI6ImNsaWVudGlkOm9pZDphdXRoY29kZTpwcm9jcmV0dXJuY29kZTpyZXNwb25zZTptZHN0YXR1czpjYXZ2OmVjaTptZDpybmQ6IiwiaGFzaHBhcmFtc3ZhbCI6IjMwNjkxMjk3MWFiMmY5MDItNTYyYi00ZjVhLWI5N2QtNjY1YmI4YWU5ODVmMTAzMzI3MDBBcHByb3ZlZDFBQUlCQXBjaE13QUFBQ2lkbEpGeWRBQUFBQUE9MDVhVzVrWlhnNk1ESnZoaGZoaWRGR25hSEx4N09rdVhJSnh4Z2IzRm5EeGZlSzhZc2NVSVJ6YnFqbkYxZmY1RmY3WVdKUkt3cnYwL0psQzdOaUI0WHNzY2V2aUlWVW5GVUV3ZDRWZWRvTWsvMkk1U2xKdWJOTWlleFlWbDJ5bURMRm8vSnVqY3U1NHN0THNSRDY5dXczMlIvdytGVlNyZWNmcmFFN2t3aDNjV1pRZXBuMFpWcExnSmpGeFVXeVcyeXJYYlEyV0JtdTBlRXIreW5naUxDbVFaMEYvTjBZcURUYnAvaThBanBWZ1JLbUVYck1KRjJDIiwiY2xpZW50aWQiOiIzMDY5MTI5NyIsIk1hc2tlZFBhbiI6IjQ4MjQ4OTI0KioqKjUwMTgiLCJ0eG50aW1lc3RhbXAiOiIxNjg3Mzc2NTgyOTE5IiwiZXJyb3J1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJ0eG50aW1lb3V0cGVyaW9kIjoiNjAiLCJ0ZXJtaW5hbHByb3Z1c2VyaWQiOiJQUk9WQVVUIiwic2VjdXJlM2RoYXNoIjoiMzQ2MjJBNERDNzM0OURCMDAyMzg5RjIwNDk0NkUwMzc4OTU2RDc4OSIsImNhcmRuYW1lIjoidGVzdCIsInJlZnJlc2h0aW1lIjoiMCIsImN1c3RvbWVyZW1haWxhZGRyZXNzIjoidGVzdEB0ZXN0LmNvbSIsInNlY3VyZTNkc2VjdXJpdHlsZXZlbCI6IjNEX0ZVTEwiLCJ0eG5pbnN0YWxsbWVudGNvdW50IjoiNSIsInN1Y2Nlc3N1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJ0b3RhbGxpbnN0YWxsbWVudGNvdW50IjoiNSIsInRlcm1pbmFsbWVyY2hhbnRpZCI6IjcwMDA2NzkiLCJsYW5nIjoidHIiLCJhZGRjYW1wYWlnbmluc3RhbGxtZW50IjoiTiIsInR4bmFtb3VudCI6IjEwMzk3IiwiaW5zdGFsbG1lbnRvbmx5Zm9yY29tbWVyY2lhbGNhcmQiOiJOIiwidHhuY3VycmVuY3ljb2RlIjoiOTQ5IiwibW9kZSI6IlRFU1QiLCJ0ZXJtaW5hbHVzZXJpZCI6IjMwNjkxMjk3Iiwib3JkZXJpZCI6IjFhYjJmOTAyLTU2MmItNGY1YS1iOTdkLTY2NWJiOGFlOTg1ZiIsImN1c3RvbWVyaXBhZGRyZXNzIjoiMS4xLjEuMSIsImFwaXZlcnNpb24iOiJ2MC4wMSIsInR4bnR5cGUiOiJzYWxlcyIsImNvbXBhbnluYW1lIjoiSGV4Y2FwIiwiY2FtcGFpZ25jaG9vc2VsaW5rIjoiaHR0cHM6Ly9zYW5hbHBvc3Byb3Z0ZXN0LmdhcmFudGliYnZhLmNvbS50ci9zZXJ2bGV0L2NhbXBhaWduY2hvb3NlP2NhbXBhaWduS2V5PTgyRUM2MzkxNzM0NTAzMjg4NTA0RDkwNDkzNDI1NDU2NDRERDlCNDMifQ==";
        byte[] callBackBodyDecoded = Base64.getDecoder().decode(encodedCallBackBody);
        String callBackBody = new String(callBackBodyDecoded);
        CallBackService callBackService = new ICallBackService();
        boolean result = callBackService.validate(callBackBody,"12345678" );
        System.out.println(result);
        assert result;
    }
}
